spring:
  application:
    name: account-service
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/account-serviceDb
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

server:
  port: 8080

rabbitmq:
  queue:
    account:
      name: account-queue
    transaction:
      name: transaction-queue
  exchange:
    name: bank-exchange
  routingKey:
    account:
      key: account-routing-key
    transaction:
      key: transaction-routing-key
